stages:
  - build-push
  - push-manifest

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: "aron666/storj-identity"
  TAG_LATEST: "latest"
  BRANCH: main
  TAG_VERSION: "1.0.0.1"
  DOCKER_TLS_CERTDIR: "" # 禁用 TLS 驗證

# 定義 Docker login 的全局設置
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build-amd64:
  stage: build-push
  tags:
    - amd64
  image: docker:latest # 使用 Docker 官方鏡像
  services:
    - docker:dind # 使用 Docker-in-Docker
  script:
    - docker build --build-arg TARGETARCH=amd64 -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:amd64-$TAG_LATEST # 標記為 latest
    - docker push $IMAGE_NAME:amd64-$TAG_LATEST
    - docker rmi $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:amd64-$TAG_LATEST
  only:
    - main # 僅當 main 分支有變更時觸發

build-arm64:
  stage: build-push
  tags:
    - arm64
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --build-arg TARGETARCH=arm64 -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:arm64-$TAG_LATEST
    - docker push $IMAGE_NAME:arm64-$TAG_LATEST
    - docker rmi $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:arm64-$TAG_LATEST
  only:
    - main



push-manifest:
  stage: push-manifest
  tags:
    - amd64
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull $IMAGE_NAME:amd64-$TAG_LATEST
    - docker pull $IMAGE_NAME:arm64-$TAG_LATEST
    - docker manifest create $IMAGE_NAME:$TAG_VERSION $IMAGE_NAME:amd64-$TAG_LATEST $IMAGE_NAME:arm64-$TAG_LATEST
    - docker manifest push $IMAGE_NAME:$TAG_VERSION
    - docker manifest create $IMAGE_NAME:$TAG_LATEST $IMAGE_NAME:amd64-$TAG_LATEST $IMAGE_NAME:arm64-$TAG_LATEST
    - docker manifest push $IMAGE_NAME:$TAG_LATEST
    - docker rmi $IMAGE_NAME:amd64-$TAG_LATEST $IMAGE_NAME:arm64-$TAG_LATEST
  only:
    - main