version: '3'
services:
  storj-identity:
    image: aron666/storj-identity
    environment:
      EMAIL_TOKEN: "email:token" 
    volumes:
      - ./identity:/root/.local/share/storj/identity
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        TARGETARCH: amd64
